# held-item ids, used to colour the handheld light by what light source is being held
# (see clHeldLightColor() in /lib/colored_lighting/applyColoredLight.glsl)

item.4101 = soul_torch soul_lantern soul_campfire
item.4102 = redstone_torch
item.4103 = sea_lantern
item.4104 = verdant_froglight
item.4105 = ochre_froglight
item.4106 = pearlescent_froglight
item.4107 = amethyst_cluster amethyst_shard
item.4108 = lantern
item.4109 = glowstone
item.4110 = shroomlight
item.4111 = magma_block
item.4112 = end_rod
item.4113 = torch
item.4114 = campfire
item.4115 = jack_o_lantern
item.4116 = crying_obsidian
item.4117 = beacon
item.4118 = conduit
item.4119 = glow_berries
